### ISSUE TITLE
Stopping on exception not working

### ISSUE THREAD

**Issue by kinnarr** [metricq/metricq-source-bacnet#9]
After stopping from an unhandled exception, "starts" stopping the source, but didn't complet

**Comment by kinnarr** [comment]
```
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,375 [ERROR ] [metricq.agent ] Exception in event loop: Task exception was never retrieved
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,376 [ERROR ] [metricq.agent ] Future: <Task finished name='Task-313' coro=<BacnetSource._worker_task() done,
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,376 [ERROR ] [metricq.agent ] Stopping Agent on unhandled exception (TimeoutError)
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,377 [ERROR ] [metricq.agent ] Exception in event loop: Task exception was never retrieved
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,377 [ERROR ] [metricq.agent ] Future: <Task finished name='Task-230' coro=<BacnetSource._worker_task() done,
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,377 [ERROR ] [metricq.agent ] Stopping Agent on unhandled exception (TimeoutError)
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,378 [ERROR ] [metricq.agent ] Exception in event loop: Task exception was never retrieved
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,378 [ERROR ] [metricq.agent ] Future: <Task finished name='Task-306' coro=<BacnetSource._worker_task() done,
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,378 [ERROR ] [metricq.agent ] Stopping Agent on unhandled exception (TimeoutError)
Nov 20 15:12:31 metricq-source-bacnet[36061]: 2020-11-20 15:12:31,379 [ERROR ] [metricq_source_bacnet.source] Source stopping by unhandled exception
Nov 20 15:12:31 metricq-source-bacnet[36061]: Traceback (most recent call last):
Nov 20 15:12:31 metricq-source-bacnet[36061]: File "/usr/local/lib/python3.8/site-packages/metricq_source_bacnet/source.py", line 360, in _worker_task
Nov 20 15:12:31 metricq-source-bacnet[36061]: await self.declare_metrics(metrics)
Nov 20 15:12:31 metricq-source-bacnet[36061]: File "/usr/local/lib/python3.8/site-packages/metricq/source.py", line 91, in declare_metrics
Nov 20 15:12:31 metricq-source-bacnet[36061]: await self.rpc("source.declare_metrics", metrics=metrics)
Nov 20 15:12:31 metricq-source-bacnet[36061]: File "/usr/local/lib/python3.8/site-packages/metricq/client.py", line 108, in rpc
Nov 20 15:12:31 metricq-source-bacnet[36061]: return await super().rpc(
Nov 20 15:12:31 metricq-source-bacnet[36061]: File "/usr/local/lib/python3.8/site-packages/metricq/agent.py", line 381, in rpc
Nov 20 15:12:31 metricq-source-bacnet[36061]: return await asyncio.wait_for(request_future, timeout=timeout)
Nov 20 15:12:31 metricq-source-bacnet[36061]: File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
Nov 20 15:12:31 metricq-source-bacnet[36061]: raise exceptions.TimeoutError()
Nov 20 15:12:31 metricq-source-bacnet[36061]: asyncio.exceptions.TimeoutError
```
